# Generated by Django 5.2 on 2026-06-05 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('match_level', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak')], max_length=10)),
                ('summary_uz', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('annotations', models.JSONField(default=list)),
                ('missing_uz', models.JSONField(default=list)),
                ('strengths_uz', models.JSONField(default=list)),
                ('breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_analyses', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
