# Generated by Django 5.2 on 2026-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanalysis',
            name='essay_text',
            field=models.TextField(blank=True),
        ),
    ]
