# Generated by Django 5.2 on 2026-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('university', 'University'), ('grant', 'Grant')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('required_documents', models.JSONField(default=list)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('min_ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
